CREATE TABLE ROLES(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  ROLE_NAME VARCHAR(15) NOT NULL
);

CREATE TABLE USER_TO_ROLE (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  FK_USER_ID BIGINT NOT NULL,
  FK_ROLE_ID BIGINT NOT NULL,
  CONSTRAINT FK_UTR_TO_USERS FOREIGN KEY (FK_USER_ID)
  REFERENCES USERS(ID),
  CONSTRAINT FK_UTR_TO_ROLES FOREIGN KEY (FK_ROLE_ID)
  REFERENCES ROLES(ID)
);

  CREATE TABLE CART (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FK_PRODUCT_ID BIGINT NOT NULL,
    FK_USER_ID BIGINT,
    TEMP_TOKEN VARCHAR(255),
    CONSTRAINT FK_C_TO_PRODUCTS FOREIGN KEY (FK_PRODUCT_ID)
    REFERENCES PRODUCTS(ID),
    CONSTRAINT FK_C_TO_USERS FOREIGN KEY (FK_USER_ID)
    REFERENCES USERS(ID)
  );

CREATE TABLE ORDERS (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  PRICE DOUBLE NOT NULL,
  FK_USER_ID BIGINT NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL,
  PAYMENT_TIME TIMESTAMP,
  CONSTRAINT FK_O_TO_USERS FOREIGN KEY (FK_USER_ID)
  REFERENCES USERS(ID)
)

CREATE TABLE ORDER_PRODUCTS (
  FK_ORDER_ID BIGINT NOT NULL,
  FK_PRODUCT_ID BIGINT NOT NULL,
  CONSTRAINT FK_OP_TO_USERS FOREIGN KEY (FK_ORDER_ID)
  REFERENCES ORDERS(ID),
  CONSTRAINT FK_OP_TO_ROLES FOREIGN KEY (FK_PRODUCT_ID)
  REFERENCES PRODUCTS(ID)
)